// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgresDb;

#nullable disable

namespace PostgresDb.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20260303152014_InitialCreateZontDevices")]
    partial class InitialCreateZontDevices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostgresDb.ZontEntities.ZontDeviceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_model");

                    b.Property<DateTime?>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("HardwareVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hardware_version");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("software_version");

                    b.Property<int>("ZontId")
                        .HasColumnType("integer")
                        .HasColumnName("zont_id");

                    b.HasKey("Id");

                    b.HasIndex("ZontId")
                        .HasDatabaseName("ix_zont_devices_zont_id");

                    b.ToTable("zont_devices", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
